### ISSUE TITLE
Feature request: allow reaction to no matched/empty key

### ISSUE THREAD

**Issue by cschleiden** [github/text-expander-element#10]
It would be great if `text-expander` would provide an option or event to show a suggestion menu if no key matches, or to allow specifying an empty key. 

Example usage scenario:
Providing a list of supported keys to aid discoverability. 
![image](https://user-images.githubusercontent.com/2201819/67905944-5683f000-fb30-11e9-9aa8-a3bf6a904a02.png)

/cc @github/web-systems

**Comment by koddsson** [comment]
@cschleiden I'm not sure how this would work, could you elaborate further? The screenshot linked isn't a `<text-expander>` as far as I know.

Discoverability right now just works by showing you available items when you input a specified key in an input. For example, the component will list up all the emojis when you type `:` in a GitHub issue comment box.

![image](https://user-images.githubusercontent.com/318208/71007655-45db0980-20df-11ea-85d4-c41c49f5fddd.png)

And if there are no results, just nothing is displayed:

<img width="395" alt="Screenshot 2019-12-17 at 15 10 11" src="https://user-images.githubusercontent.com/318208/71007703-5b503380-20df-11ea-861e-f272cdcedc6c.png">

**Comment by muan** [comment]
@koddsson context here: https://github.com/github/github/pull/127881#discussion_r339164679

**Comment by cschleiden** [comment]
@koddsson We have a few places in the product where we use the kind of filter input experience I showed in the screenshot. Most recently I built it for workflow/actions filtering:
![image](https://user-images.githubusercontent.com/2201819/71011219-e8749780-20a1-11ea-9782-66b3915f2240.png)


We don't have any shared components for this filter input, so it involved a fair amount of custom javascript. `text-expander` looks like it could provide most of that async auto complete functionality, if there was only a way to show that initial options dropdown.

**Comment by muan** [comment]
Having thought about this more, I think this behavior should not be covered by text-expander. The pieces needed to develop this feature are available through https://github.com/github/combobox-nav. We have yet found another use case for this pattern, though there are indeed variations of similar behaviors being tested, though each of them is slightly different. We can revisit generalizing this kind of behavior at a later date, independent of text-expander. 

Thanks for opening this issue!
