### ISSUE TITLE
Results do not show when used in shadowDOM

### ISSUE THREAD

**Issue by alexanderjulmer** [github/text-expander-element#24]
If I am not mistaken, this check https://github.com/github/text-expander-element/blob/3a48da5b7e8b1f2d2e9c07a4019962856e29f140/src/text-expander-element.ts#L74 might cause issues if `text-expander-element` is used inside another component's shadow DOM:

```html
<parent-component>
  <text-expander>
    <textarea>
  </text-expander>
</parent-component>
```

Chrome and Safari alike return `parent-component` as `document.activeElement` rather than the `textarea` when the textarea is focussed. If I understand correctly, the above check is meant to turn off results once the focus moves away which is not the case.

I think changing it to 

```js
if (this.input !== document.activeElement && this.input !== document.activeElement.shadowRoot?.activeElement) return
```

would resolve that issue but I might not fully oversee unintended consequences.

**Comment by keithamus** [comment]
Hey @alexanderjulmer thanks for the issue, it looks like a reasonable change to me! Would you like to open up a PR - with perhaps some tests, so we can look into merging it?

**Comment by alexanderjulmer** [comment]
Hey @keithamus, for sure. I opened #25 but I am fairly new to this so feedback is greatly appreciated.

**Comment by dgreif** [comment]
Closed by #25

**Comment by keithamus** [comment]
Great work @alexanderjulmer! Thanks for working on this!

**Comment by alexanderjulmer** [comment]
Time for another round. The solution I've implemented only works for one level of nesting as it only checks the active element's shadow root.

https://github.com/github/text-expander-element/blob/489371b76789c260a6d5feb6aadd5bae6982a922/src/text-expander-element.ts#L74

This does not work if the element is nested in more than one CustomElement with a shadow root. I guess one could recursively check the document's active element and the document's active element's shadow root, which then becomes the document. This seems cumbersome though.

```js
const active = checkIsActive(this.input, document)

function checkIsActive(input, document) {
  if (input == document.activeElement) {
    return true
  } else if (!!document.activeElement.shadowRoot) {
    return checkIsActive(input, document.activeElement.shadowRoot)
  } else {
    return false
  }
}
```

Maybe there's a more elegant way that I am not aware of?
