### ISSUE TITLE
Space being unavoidably added

### ISSUE THREAD

**Issue by silverwind** [github/text-expander-element#35]
There is an unavoidable space character being appended target element's `value` during the `text-expander-value` event:

https://github.com/github/text-expander-element/blob/5b5f7ad1056327f1d297be8474fb689089115cb9/src/text-expander-element.ts#L128

Could this be removed or made optional? I think the consumer of the module should be in control of whether they want this space, or not.

**Comment by keithamus** [comment]
Thanks for the issue! PRs welcome to add the optionality.

**Comment by silverwind** [comment]
How do you feel about removing it and pushing v3.0.0 with it?

**Comment by keithamus** [comment]
We’d like to retain the behaviour so if you think it’s undesirable for your usecase, then we can make it an option (eg a suffix attribute which defaults to a space)

**Comment by silverwind** [comment]
Okay, so an attribute on the HTML node it is then. Will default to single space as currently.

BTW my use case might be something for GitHub to consider too:

- On a `@` mention, the space is desirable as one usually starts a sentence with a mention.
- On a `:` emoji, the space is undesirable as it's often used to end a sentence.

**Comment by silverwind** [comment]
Actually, HTML option will work as well when set to the empty string as the optional space can be appended during the `event.detail.value` assignment based on `key`.
