### ISSUE TITLE
The UX is broken with v2.3.0 of @github/combobox-nav dependency

### ISSUE THREAD

**Issue by StanBright** [github/text-expander-element#50]
A quick report that `v2.3.0 of @github/combobox-nav` and the new scrollIntoView broke the UX of @github/text-expander for me. It would push the expanded `<ul>` to the top of the screen. Also, when I scroll down with the keyboard over the available options (`<li>` elements), it would try to move the highlighted element to the top of the screen. After spending a few hours debugging what's the core of the issue, I noticed that the undesirable UX happens after the combobox-nav dependency of text-expander is upgraded to v2.3.0.

I think this is the PR that's bugging the behaviour https://github.com/github/combobox-nav/pull/75

If someone else is facing this issue, my solution was to fix combobox-nav to v2.2.0 through "resolutions" section of package.json.

**Comment by keithamus** [comment]
Would you kindly provide a reduced test case and we can look into it.

**Comment by wxiaoguang** [comment]
Here is the sample for the bug:

* https://github.com/go-gitea/gitea/issues/28595

**Comment by wxiaoguang** [comment]
It should use "nearest" behavior IMO.

**Comment by keithamus** [comment]
If you want to raise a PR with the default to `nearest` I'd happily merge and release, and hopefully it resolves the issue.

**Comment by wxiaoguang** [comment]
Use "nearest" behavior for scrollIntoView #79 

Does it look good to you? Feel free to edit it directly or replace it. Thank you.

**Comment by keithamus** [comment]
https://github.com/github/combobox-nav/releases/tag/v2.3.1
